@startuml

title "Bible Reader Classes"

package models {
    class Bible {
        Bible Model
    }
    class Verse {
        Verse Model
    }
    Verse -up-* Bible
}

package bibles {
    class AbstractReader{
        Abstract Reader for all Bible APIs
        ----
        +get(self, *args, **kwargs)
        +prepare_url(self, *args, **kwargs)
        +prepare_response(self, data)
    }
    class BaseReader{
        Base Reader Class
        ----
        +__init__(self, url: str)
        +request(self, url: str)
    }
    package bible{
        class BibleReader{
            The class to read the Bible
            from the REST API
            ----
            +get(self, book: str, chapter: int, verse: int)
        }
    }
    package ron_swanson{
        class RonSwansonReader{
            The class to read Ron Swanson's quotes
            from the REST API
            ----
            +get(self, term: str)
        }
    }
    package office{
        class TheOfficeReader{
            The class to read The Office Quotes
            from the REST API
            ----
            +get(self)
        }
    }
    BaseReader -up-> AbstractReader

    BibleReader -up-> BaseReader: Inherit constructor
    RonSwansonReader -up-> BaseReader: Inherit constructor
    TheOfficeReader -up-> BaseReader: Inherit constructor
}
Bible -up-o BibleReader
Bible -up-o RonSwansonReader
Bible -up-o TheOfficeReader

@enduml